name: Java HelloWorld CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
      - name: Compile HolaMundo
        run: javac HolaMundo.java
      - name: Run HolaMundo
        run: java HolaMundo
